-- ============================================================================
-- 补签卡 / 加分卡（《练级与奖励体系方案》§4.2 / §4.3 / §4.3.1）
--
-- 用法：psql -h <host> -p 5432 -U postgres -d postgres -v ON_ERROR_STOP=1 \
--        -f db-migration-cards.sql
--
-- 幂等，可重复执行。
--
-- ---------------------------------------------------------------------------
-- 设计裁决：余额与发放**放服务端**
--
-- 方案 §5.1 原写作「权威余额存在本地 `socio_vocab_xp.cards`」—— 那是**本地方案时代**的写法。
-- 现在打卡判定已经切到服务端，而**补签直接改变达标天数、达标天数决定全勤奖（实物出口）**
-- ⇒ 余额若留在本地，全勤奖仍有一条"改一行 localStorage 就多一天"的路径。
-- ⇒ 与 §8「打卡一并服务端化」同一理由，**余额必须在服务端**。
--
-- ---------------------------------------------------------------------------
-- 为什么是「流水 + 现算」而不是「一个余额字段」
--
-- 发放有两个来源（每周达标、等级里程碑）都需要**幂等**：某个周达标了只能发一次、
-- 某个等级节点只能发一次。用一张带唯一键的流水表，幂等由数据库保证（`on conflict do nothing`），
-- 不必在每个发放点手写"发过了吗"的判断 —— 那种判断正是重复发放的常见来源。
-- 余额则由「流水条数 − 使用条数」现算，符合本项目「总量现算、永不落盘」的既有哲学。
--
-- ⚠ 补签卡的「使用」不需要新流水：`checkin_makeups` 每条就是一次使用。
--   只有加分卡需要 `card_uses`（它的使用发生在作业加分的场景，原有表里没有落点）。
--
-- ⚠⚠ **`grant_pending_cards()` 已被 `db-migration-cards-v2.sql` 取代**
--   （2026-09-28：上线前欠账合计封顶 7 张 + 只发给学生）。
--   本文件仍需保留（表、等级换算式、`get_card_balance()` 都在这里），
--   但**重跑本文件会把 v2 的 `grant_pending_cards()` 覆盖回旧版** ⇒
--   若因任何原因重跑了本文件，**紧接着必须再跑一次 `db-migration-cards-v2.sql`**。
-- ============================================================================

-- ============================================================================
-- ① 发放流水（幂等）
-- ============================================================================
create table if not exists public.card_grants (
  id         bigint generated by default as identity primary key,
  user_id    uuid        not null,
  kind       text        not null check (kind in ('makeup', 'bonus')),
  -- ref 是「这一次发放」的唯一标识：'week:2026-09-22' / 'lv10:makeup' / 'lv25:bonus' / 'legacy:accum3'
  ref        text        not null,
  created_at timestamptz not null default now(),
  unique (user_id, kind, ref)
);

create index if not exists card_grants_user_idx on public.card_grants (user_id);

alter table public.card_grants enable row level security;

drop policy if exists card_grants_read_own on public.card_grants;
create policy card_grants_read_own on public.card_grants
  for select using (auth.uid() = user_id);

drop policy if exists card_grants_read_staff on public.card_grants;
create policy card_grants_read_staff on public.card_grants
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher', 'developer')));

-- 写只能经下面的 RPC（内部做归属与规则校验）
revoke insert, update, delete, truncate, references, trigger on public.card_grants from authenticated;
revoke all on public.card_grants from anon;

comment on table public.card_grants is
  '卡发放流水（补签卡/加分卡）。unique(user_id,kind,ref) 即幂等键；余额 = 发放 − 使用，现算。';

-- ============================================================================
-- ② 使用流水（只加分卡需要；补签卡的使用由 checkin_makeups 承担）
-- ============================================================================
create table if not exists public.card_uses (
  id         bigint generated by default as identity primary key,
  user_id    uuid        not null,
  kind       text        not null check (kind in ('makeup', 'bonus')),
  -- 加分卡：ref = 作业/测验 id（§4.2.1「每份限用 1 张」由唯一键保证）
  ref        text        not null,
  created_at timestamptz not null default now(),
  unique (user_id, kind, ref)
);

create index if not exists card_uses_user_idx on public.card_uses (user_id);

alter table public.card_uses enable row level security;

drop policy if exists card_uses_read_own on public.card_uses;
create policy card_uses_read_own on public.card_uses
  for select using (auth.uid() = user_id);

drop policy if exists card_uses_read_staff on public.card_uses;
create policy card_uses_read_staff on public.card_uses
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher', 'developer')));

revoke insert, update, delete, truncate, references, trigger on public.card_uses from authenticated;
revoke all on public.card_uses from anon;

comment on table public.card_uses is
  '卡使用流水。ref 对加分卡是作业/测验 id（§4.2.1 每份限用 1 张，由唯一键保证）。';

-- ============================================================================
-- ③ 等级换算式（与前端 `app/src/lib/xpLevel.ts` 同一条曲线）
--
-- ⚠ 两处必须一致，否则会出现「前端显示 LV10、服务端按 LV9 发卡」这类静默错位。
--   曲线：`LV(n) → LV(n+1)` 需要 `120 + 10×(n-1)`；累计 `XP(LV k) = 5k² + 105k − 110`。
-- ============================================================================
create or replace function public.xp_for_level(p_level integer)
returns integer
language sql
immutable
as $$
  select case
           when p_level is null or p_level <= 1 then 0
           else 120 * (p_level - 1) + 10 * (p_level - 1) * (p_level - 2) / 2
         end;
$$;

create or replace function public.xp_level(p_xp integer)
returns integer
language plpgsql
immutable
as $$
declare
  v_x integer := greatest(0, coalesce(p_xp, 0));
  v_k integer;
begin
  -- 反解公式只给近似值（浮点误差）⇒ 与前端的做法一致，用公式回验各修正一步，
  -- 避免边界处差一级（那会直接体现为多发或少发一张卡）。
  v_k := greatest(1, floor((sqrt(13225 + 20 * v_x) - 105) / 10)::int);
  while public.xp_for_level(v_k + 1) <= v_x loop v_k := v_k + 1; end loop;
  while v_k > 1 and public.xp_for_level(v_k) > v_x loop v_k := v_k - 1; end loop;
  return v_k;
end $$;

comment on function public.xp_level(integer) is
  '由累计 XP 反解等级。⚠ 必须与前端 app/src/lib/xpLevel.ts 的 levelOf() 一致。';

-- ============================================================================
-- ④ grant_pending_cards()：把「该发但还没发」的卡补上（幂等）
--
-- 为什么是「读时补发」而不是定时任务：本站没有调度器，而发放规则（每周达标、等级里程碑）
-- 都可以从**已有的打卡与 XP 数据现算** ⇒ 任何人来读余额时顺手把欠的补上即可。
-- 幂等由 `card_grants` 的唯一键保证，所以重复调用只会做无用功、不会重复发。
-- ============================================================================
create or replace function public.grant_pending_cards(p_uid uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_level      integer;
  v_xp         integer;
  v_accum_days integer;
  v_best_streak integer;
  v_makeup_days integer;
begin
  if p_uid is null then
    return;
  end if;

  -- ---------- (a) 每周达标：一周 ≥100 题且正确率 ≥80% ⇒ 补签卡 1 张（§4.3）----------
  insert into public.card_grants (user_id, kind, ref)
  select p_uid, 'makeup', 'week:' || w.week_start::text
    from (
      select date_trunc('week', d.day_key)::date as week_start,
             sum(d.questions)                     as q,
             sum(d.correct)                       as c
        from public.daily_study_of(p_uid, null, null) d
       group by 1
    ) w
   where w.q >= 100 and w.q > 0 and (w.c / w.q) >= 0.8
  on conflict (user_id, kind, ref) do nothing;

  -- ---------- (b) 等级里程碑（§4.2 重排后的三档）----------
  -- XP 与前端同口径：只统计起算日之后（见 db-migration-xp-start-date.sql）
  select coalesce(sum(xp), 0) into v_xp
    from public.xp_events
   where user_id = p_uid and day_key >= date '2026-09-30';
  v_level := public.xp_level(v_xp);

  -- 每 10 级：补签卡与加分卡**交替**（LV10 补签卡 → LV20 加分卡 → LV30 补签卡 …）
  insert into public.card_grants (user_id, kind, ref)
  select p_uid,
         case when (g.lv / 10) % 2 = 1 then 'makeup' else 'bonus' end,
         'lv' || g.lv::text || ':decade'
    from generate_series(10, v_level, 10) as g(lv)
  on conflict (user_id, kind, ref) do nothing;

  -- 每 25 级：加分卡 ×1（**叠加**在上一档之上）
  insert into public.card_grants (user_id, kind, ref)
  select p_uid, 'bonus', 'lv' || g.lv::text || ':quarter'
    from generate_series(25, v_level, 25) as g(lv)
  on conflict (user_id, kind, ref) do nothing;

  -- 大节点 LV50 / 100 / 200：加分卡 ×2（特殊徽章是纯展示，不涉及发放）
  insert into public.card_grants (user_id, kind, ref)
  select p_uid, 'bonus', 'lv' || b.n::text || ':big' || s.i::text
    from (values (50), (100), (200)) as b(n)
    cross join generate_series(1, 2) as s(i)
   where b.n <= v_level
  on conflict (user_id, kind, ref) do nothing;

  -- ---------- (c) 初始发放（§4.3.1，一次性）----------
  -- 全部发补签卡：动机原文是「当时赚的补签机会要么没用上、要么被当周作废」
  -- ⇒ 补的是**补签机会**，不是加分机会。
  -- ⚠ 阈值取自 2026-09-21 的分布（从严版），方案要求上线后按实际分布复核。
  select count(*) into v_accum_days
    from public.daily_study_of(p_uid, null, null) d
   where d.makeup or (d.questions >= 20 and d.ms >= 600 * 1000);

  with days as (
    select d.day_key,
           (d.makeup or (d.questions >= 20 and d.ms >= 600 * 1000)) as ok
      from public.daily_study_of(p_uid, null, null) d
  ),
  checked as (
    select d.day_key,
           d.day_key - (row_number() over (order by d.day_key))::int as grp
      from days d
     where d.ok
  ),
  runs as (select grp, count(*) as len from checked group by grp)
  select coalesce(max(len), 0) into v_best_streak from runs;

  select count(*) into v_makeup_days
    from public.checkin_makeups m where m.user_id = p_uid;

  insert into public.card_grants (user_id, kind, ref)
  select p_uid, 'makeup', r.ref
    from (values
      ('legacy:accum3',   3,  v_accum_days),
      ('legacy:accum7',   7,  v_accum_days),
      ('legacy:accum14',  14, v_accum_days),
      ('legacy:streak3',  3,  v_best_streak),
      ('legacy:streak7',  7,  v_best_streak),
      ('legacy:streak14', 14, v_best_streak),
      ('legacy:makeup1',  1,  v_makeup_days)
    ) as r(ref, need, actual)
   where r.actual >= r.need
  on conflict (user_id, kind, ref) do nothing;
end $$;

comment on function public.grant_pending_cards(uuid) is
  '把该发但未发的卡补上（每周达标 / 等级里程碑 / 初始发放）。幂等，靠 card_grants 唯一键兜底。';

-- ============================================================================
-- ⑤ get_card_balance()：余额出口（**先补发，再现算**）
-- ============================================================================
create or replace function public.get_card_balance()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid    uuid := auth.uid();
  v_makeup integer;
  v_bonus  integer;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  perform public.grant_pending_cards(v_uid);

  -- 补签卡：发放流水 − checkin_makeups（每条补签就是一次使用）
  select count(*) into v_makeup
    from public.card_grants g
   where g.user_id = v_uid and g.kind = 'makeup';
  v_makeup := v_makeup - (select count(*) from public.checkin_makeups m where m.user_id = v_uid);

  -- 加分卡：发放流水 − 使用流水
  select count(*) into v_bonus
    from public.card_grants g
   where g.user_id = v_uid and g.kind = 'bonus';
  v_bonus := v_bonus - (select count(*) from public.card_uses u
                         where u.user_id = v_uid and u.kind = 'bonus');

  return jsonb_build_object(
    'makeup', greatest(0, v_makeup),
    'bonus',  greatest(0, v_bonus)
  );
end $$;

grant execute on function public.get_card_balance() to authenticated;

comment on function public.get_card_balance() is
  '补签卡/加分卡余额。读时先补发欠的卡，再按「发放 − 使用」现算。学生只需自己的。';
