-- ============================================================================
-- XP 体系 C 档：事件流水 + 服务端累计
-- 2026-09-23
--
-- 设计见《XP-C档改造方案.md》。本脚本**纯新增**，不改动任何现有表 / 函数 / 策略。
-- ⚠⚠⚠ **本文件已冻结，不要再整体重跑**（2026-10-08 事故后加）。
--   下面那句「幂等，可重复执行」**只在 09-23 当天成立** —— 本文件曾拥有 ③④⑤ 三个函数，
--   那三个后来**各自被更新的迁移取代**；而本文件于 **09-24 被改后重跑过一次**（`2d1b9fa`：
--   给 elapsed_ms 加上限），于是它自己那份 09-23 的旧 `get_daily_study` 被重新写出，
--   **把 09-23 12:32 装好的新版覆盖回旧版**（旧版内联查 `xp_events`，**不读 `checkin_baselines`**）。
--   后果：学生端连签 / 累计 / 最长纪录集体塌掉；而教师端走 `daily_study_of()` 不受影响
--   ⇒ **师生口径分裂**。修复见 `db-migration-fix-get-daily-study.sql`。
--   ⇒ 那三份旧定义**已于 2026-10-08 从本文件删除**（见下方 ③④⑤ 处的说明），
--     所以本文件**不再自包含**：只跑它不会建出 ③④⑤，必须连同它们各自的最新拥有者一起应用。
--
-- 组成（更正：**只有 ①②⑥ 仍归本文件所有**）：
--   ① xp_events            事件流水（唯一事实来源）
--   ② xp_of()              服务端算分（XP 表的唯一实现）
--   ③ submit_xp_events()   → 已移至 db-migration-item-cooldown.sql
--   ④ get_xp_summary()     → 已移至 db-migration-monthly.sql
--   ⑤ get_daily_study()    → 已移至 db-migration-makeup.sql
--   ⑥ checkin_baselines    历史打卡基线（一次性迁移，之后只读）
--
-- 历史声明（已被上面取代，保留以免丢失语境）：
-- 幂等，可重复执行（在 Supabase 控制台 → SQL Editor 整段执行）。
--
-- 落地方式：**鉴权可见**。本脚本建好的对象先只被 developer 账号使用，
--   学生端仍旧走本地打卡与本地 XP，切换时机见方案 §六之三。
--
-- 组成：
--   ① xp_events            事件流水（唯一事实来源）
--   ② xp_of()              服务端算分（XP 表的唯一实现）
--   ③ submit_xp_events()   上报入口（9 道防线；**只截断、不拒收**）
--   ④ get_xp_summary()     总 XP 出口（学生端与教师端共用，防口径分叉）
--   ⑤ get_daily_study()    每日打卡聚合（**替代视图**，见末尾说明）
--   ⑥ checkin_baselines    历史打卡基线（一次性迁移，之后只读）
-- ============================================================================


-- ============================================================================
-- ① 事件流水表
-- ============================================================================
create table if not exists public.xp_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null,
  event_id    uuid        not null,                     -- 客户端生成，幂等键
  kind        text        not null,                     -- answer | chain_complete
  item_id     text        not null,
  mode        text        not null,                     -- PracticeMode 七种
  correct     boolean     not null,
  score       numeric(3,2) not null,                    -- 0 / 0.5 / 1
  elapsed_ms  integer,                                  -- 该题用时（客户端声明）；NULL = 时长不计
  answered_at timestamptz not null,                     -- 客户端声明（归日 + 补报窗口）
  received_at timestamptz not null default now(),       -- 服务端接收时刻
  day_key     date        not null,                     -- 按 Asia/Shanghai 折算
  session_id  uuid,                                     -- 一次练习会话；chain_complete 靠它防重复
  -- 接龙完成事件的变体（仅 kind='chain_complete' 时有值）：
  --   分值取决于「路线」与「作答方式」，服务端据此查表，客户端不得直接指定 XP
  chain_mode  text,                                     -- open | target
  chain_kind  text,                                     -- choice | input
  xp          integer     not null default 0,           -- **服务端**算出的分值（已应用每日裁剪）
  suspicious  boolean     not null default false,
  unique (user_id, event_id)
);

-- 约束单独加（放在 if not exists 之外，便于给已存在的表补约束）
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'xp_events_kind_chk') then
    alter table public.xp_events add constraint xp_events_kind_chk
      check (kind in ('answer', 'chain_complete'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_mode_chk') then
    -- 防线 #3 模式白名单：逐条列明七种，勿简写
    alter table public.xp_events add constraint xp_events_mode_chk
      check (mode in ('choice','spelling','matching','crossword','cloze','chain','definition'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_score_chk') then
    alter table public.xp_events add constraint xp_events_score_chk
      check (score >= 0 and score <= 1);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_elapsed_chk') then
    alter table public.xp_events add constraint xp_events_elapsed_chk
      check (elapsed_ms is null or elapsed_ms >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_xp_chk') then
    alter table public.xp_events add constraint xp_events_xp_chk check (xp >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_chain_mode_chk') then
    alter table public.xp_events add constraint xp_events_chain_mode_chk
      check (chain_mode is null or chain_mode in ('open','target'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_chain_kind_chk') then
    alter table public.xp_events add constraint xp_events_chain_kind_chk
      check (chain_kind is null or chain_kind in ('choice','input'));
  end if;
end $$;

create index if not exists xp_events_user_day_idx  on public.xp_events (user_id, day_key);
create index if not exists xp_events_user_item_idx on public.xp_events (user_id, item_id, answered_at desc);

-- 防线 #6：一局接龙只结算一次（按 session）
create unique index if not exists xp_events_chain_uniq
  on public.xp_events (user_id, session_id)
  where kind = 'chain_complete' and session_id is not null;

-- ---- RLS：学生只读自己的；教师/开发者可读全校；**没有任何写策略** ----
-- 写只能通过下面的 security definer RPC，学生无法直接 INSERT/UPDATE/DELETE。
alter table public.xp_events enable row level security;

drop policy if exists xp_events_read_own on public.xp_events;
create policy xp_events_read_own on public.xp_events
  for select using (auth.uid() = user_id);

drop policy if exists xp_events_read_staff on public.xp_events;
create policy xp_events_read_staff on public.xp_events
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher','developer')));

-- 最小权限：TRUNCATE 不受 RLS 约束，直接收掉（同 ocr_pages 的做法）
revoke truncate, references, trigger on public.xp_events from authenticated;
revoke all on public.xp_events from anon;

comment on table public.xp_events is
  'XP 事件流水（C 档唯一事实来源）。学生只读自己的，写只能经 submit_xp_events()。xp 已应用每日 400 裁剪。';


-- ============================================================================
-- ② xp_of()：服务端算分 —— XP 表的唯一实现
--   数值见《练级与奖励体系方案.md》§2.1 / §2.1.1
-- ============================================================================
create or replace function public.xp_of(
  p_kind       text,
  p_mode       text,
  p_score      numeric,
  p_chain_mode text default null,
  p_chain_kind text default null
) returns integer
language sql
immutable
as $$
  select case
    -- 接龙：**按完成结算**，每步的 answer 事件给 0；走完一局才给分
    when p_kind = 'chain_complete' then
      case
        when p_chain_mode = 'open'   and p_chain_kind = 'choice' then 20
        when p_chain_mode = 'open'   and p_chain_kind = 'input'  then 30
        when p_chain_mode = 'target' and p_chain_kind = 'choice' then 25
        when p_chain_mode = 'target' and p_chain_kind = 'input'  then 35
        else 0
      end
    when p_mode = 'chain' then 0                    -- 接龙每一步不计 XP（只计题数与掌握度）
    when p_mode = 'definition' then
      case when p_score >= 0.9 then 10              -- 全对
           when p_score >  0   then  5              -- 部分正确
           else 2 end                               -- 错
    else
      case
        when p_score >= 0.9 then                    -- 答对
          case p_mode when 'spelling' then 8 when 'cloze' then 7 when 'crossword' then 6
                      when 'matching' then 5 when 'choice' then 4 else 0 end
        when p_score > 0 then                       -- 部分正确（取约半数）
          case p_mode when 'spelling' then 4 when 'cloze' then 4 when 'crossword' then 3
                      when 'matching' then 3 when 'choice' then 2 else 0 end
        else                                        -- 答错（保底）
          case p_mode when 'spelling' then 2 when 'cloze' then 2 when 'crossword' then 2
                      when 'matching' then 1 when 'choice' then 1 else 0 end
      end
  end
$$;

comment on function public.xp_of(text, text, numeric, text, text) is
  'XP 表唯一实现（服务端算分）。客户端只报「做了什么」，绝不报「值多少 XP」。';


-- ============================================================================
-- ③ submit_xp_events()：上报入口
--
-- 九道防线（2026-09-23 版）：
--   #1 幂等        unique(user_id,event_id) + on conflict do nothing
--   #2 补报窗口    answered_at ∈ [now()-72h, now()+5min]
--                 且**不落在已结算月份**（本月；月初 1~3 日额外允许上月）
--   #3 模式白名单  mode ∈ 七种（表约束 + 这里给友好错误）
--   #4 用时下限    <500ms ⇒ 按 500ms 计（**截断，不拒收**）；缺失 ⇒ NULL
--   #5 同题去重    同 item + 同 kind，60 秒内只收一条
--   #6 接龙唯一    unique(user_id,session_id) where kind='chain_complete'
--   #7 词条存在性  **本版暂缓**（见文件末尾说明：XP 计算不依赖 item_id）
--   #8 每日裁剪    按 day_key 累计练习 XP，当日上限 400（超出部分 xp 记 0，事件仍保留）
--   #9 异常标记    整批 elapsed_ms 全相同 ⇒ suspicious = true（只标记，不拒绝）
--
-- 原则：**宁可少算，不要丢事件** —— 除补报超窗口外，一律接收。
-- ============================================================================
-- ============================================================================
-- ③④⑤ 三个函数**已于 2026-10-08 从本文件移除**
--
-- 它们曾在此定义，但各自已被更新的迁移取代；而本文件被重跑过一次，
-- 正是那次重跑把 `get_daily_study` 覆盖回了**不读基线**的旧版（详见文件头）。
-- 现在每个函数**只有一处定义**：
--   · submit_xp_events()  → db-migration-item-cooldown.sql
--   · get_xp_summary()    → db-migration-monthly.sql
--   · get_daily_study()   → db-migration-makeup.sql
-- ⚠ 本文件**不再自包含**：只跑它不会建出这三个函数。
-- ============================================================================

-- ============================================================================
-- ⑥ checkin_baselines：历史打卡基线（一次性迁移，之后只读）
--
-- 为什么需要它：打卡判定要切到服务端（`get_daily_study` 从 xp_events 聚合），
--   但事件流水是**从上线那天才开始记的** —— 在此之前学生已积累了大量打卡记录
--   （2026-09-21 的审计导出：20 条记录 / 105 个练习日）。若不迁移，
--   上线当天全体学生的「历史打卡」会集体归零，streak 与月度全勤都会断掉。
--
-- 口径：服务端最终值 = 本表 + `get_daily_study` 的当日值，**按 day_key 合并求和**
--   （**不是取 max** —— 同一天可能既有历史基线、又有上线后的新事件）。
--
-- 数据来源：`checkin-xp-audit-2026-09-21.json`（逐日 questions / seconds / correct）。
--   由脚本生成 INSERT，**一次性导入、之后只读**。
-- ============================================================================
create table if not exists public.checkin_baselines (
  user_id   uuid         not null,
  day_key   date         not null,
  questions integer      not null default 0,
  seconds   integer      not null default 0,
  correct   numeric(6,2) not null default 0,
  primary key (user_id, day_key)
);

-- RLS 与 xp_events 同口径：学生只读自己的，教师/开发者可读全校。
-- 历史基线**不接受客户端写入**（只由迁移脚本导入），因此不设任何写策略。
alter table public.checkin_baselines enable row level security;

drop policy if exists checkin_baselines_read_own on public.checkin_baselines;
create policy checkin_baselines_read_own on public.checkin_baselines
  for select using (auth.uid() = user_id);

drop policy if exists checkin_baselines_read_staff on public.checkin_baselines;
create policy checkin_baselines_read_staff on public.checkin_baselines
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher','developer')));

revoke truncate, references, trigger on public.checkin_baselines from authenticated;
revoke all on public.checkin_baselines from anon;

comment on table public.checkin_baselines is
  '历史打卡基线（2026-09-21 审计导出一次性迁移，之后只读）。服务端口径 = 本表 + xp_events 当日聚合，按 day_key 求和。';


-- ============================================================================
-- 两点说明
-- ============================================================================
-- 1) 防线 #7「词条存在性」本版**暂缓**。
--    原因：XP 的计算只依赖 mode/score/kind，**完全不依赖 item_id**，
--    所以伪造 item_id 拿不到额外 XP，它只影响「同题去重」的精度。
--    而校验 item_id 需要查 vocab_releases 的大 jsonb（慢），收益不抵成本。
--    ⇒ 若将来需要，可另加定时任务批量核对。
--
-- 2) 历史打卡迁移（checkin_baselines）**不在本脚本内**，
--    待本脚本执行完成、且前端接入验证通过后再单独生成（由 2026-09-21 审计 JSON 派生）。
