-- 定义题：模型理解（restate）+ 学生质疑 + 质疑奖励（经验值加分）
-- 2026-09-22
--
-- 背景：判分目前只给出「踩到哪条要素」（coverage），学生与教师看到判错时无法区分
--   「学生确实没说」与「模型理解错了」—— 二者需要完全不同的处理。故：
--   1) 存档模型的「第一步」输出 restate（它把学生答案理解成了什么）；
--   2) 给学生一个「我认为判错了」的入口（disputed / dispute_note / disputed_at）；
--   3) 教师若认定质疑有价值，可签发经验值加分（student_xp_bonus）。
--
-- 为什么加分要独立成表：XP 体系（见「练级与奖励体系方案.md」）尚未实现，且 XP 由本地累计、
--   student_data 是整包覆盖 —— 教师写进 student_data 会被学生下一次同步覆盖掉。
--   独立表由教师写、学生只读；将来 XP 上线时，只需 总XP = 本地XP + sum(amount) 即可合并。

-- ============ 1) definition_attempts 增加字段 ============
alter table public.definition_attempts
  add column if not exists restate      jsonb default '[]'::jsonb,   -- 模型理解（string[]）
  add column if not exists disputed     boolean default false,       -- 学生是否质疑了本次判分
  add column if not exists dispute_note text,                        -- 学生的质疑说明
  add column if not exists disputed_at  timestamptz;

comment on column public.definition_attempts.restate is '判分模型的第一步输出：它把学生答案理解成了哪些含义';
comment on column public.definition_attempts.disputed is '学生是否对本次判分提出质疑';

-- ============ 2) 学生提交质疑的 RPC ============
-- 用 security definer + 归属校验，避免为「整表 UPDATE」开策略（学生只该能改自己的质疑字段）
create or replace function public.submit_definition_dispute(
  p_attempt_id bigint,
  p_note text default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  update definition_attempts
     set disputed    = true,
         dispute_note = nullif(left(coalesce(p_note, ''), 500), ''),
         disputed_at  = now()
   where id = p_attempt_id
     and user_id = auth.uid();      -- 只能质疑自己的作答

  if not found then
    raise exception 'attempt not found or not owned by caller';
  end if;
end $$;

grant execute on function public.submit_definition_dispute(bigint, text) to authenticated;

-- ============ 3) 质疑奖励（教师签发的经验值加分） ============
create table if not exists public.student_xp_bonus (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  amount      integer not null check (amount > 0),
  reason      text,
  attempt_id  bigint references public.definition_attempts(id) on delete set null,
  created_by  uuid,
  created_at  timestamptz not null default now()
);

create index if not exists student_xp_bonus_user_idx on public.student_xp_bonus (user_id);
-- 同一次作答只发一次奖励：防止教师重复点击
create unique index if not exists student_xp_bonus_attempt_uniq
  on public.student_xp_bonus (attempt_id) where attempt_id is not null;

alter table public.student_xp_bonus enable row level security;

drop policy if exists student_xp_bonus_read_own on public.student_xp_bonus;
create policy student_xp_bonus_read_own on public.student_xp_bonus
  for select using (auth.uid() = user_id);

drop policy if exists student_xp_bonus_read_staff on public.student_xp_bonus;
create policy student_xp_bonus_read_staff on public.student_xp_bonus
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher', 'developer')));

drop policy if exists student_xp_bonus_insert_staff on public.student_xp_bonus;
create policy student_xp_bonus_insert_staff on public.student_xp_bonus
  for insert with check (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher', 'developer')));

drop policy if exists student_xp_bonus_delete_staff on public.student_xp_bonus;
create policy student_xp_bonus_delete_staff on public.student_xp_bonus
  for delete using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher', 'developer')));

comment on table public.student_xp_bonus is '教师签发的经验值加分（如：质疑被认定有价值）。学生只读；XP 体系上线后按 sum(amount) 合并';
