-- ============================================================================
-- XP 体系 C 档：事件流水 + 服务端累计
-- 2026-09-23
--
-- 设计见《XP-C档改造方案.md》。本脚本**纯新增**，不改动任何现有表 / 函数 / 策略。
-- 幂等，可重复执行（在 Supabase 控制台 → SQL Editor 整段执行）。
--
-- 落地方式：**鉴权可见**。本脚本建好的对象先只被 developer 账号使用，
--   学生端仍旧走本地打卡与本地 XP，切换时机见方案 §六之三。
--
-- 组成：
--   ① xp_events            事件流水（唯一事实来源）
--   ② xp_of()              服务端算分（XP 表的唯一实现）
--   ③ submit_xp_events()   上报入口（9 道防线；**只截断、不拒收**）
--   ④ get_xp_summary()     总 XP 出口（学生端与教师端共用，防口径分叉）
--   ⑤ get_daily_study()    每日打卡聚合（替代视图，见末尾说明）
-- ============================================================================


-- ============================================================================
-- ① 事件流水表
-- ============================================================================
create table if not exists public.xp_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null,
  event_id    uuid        not null,                     -- 客户端生成，幂等键
  kind        text        not null,                     -- answer | chain_complete
  item_id     text        not null,
  mode        text        not null,                     -- PracticeMode 七种
  correct     boolean     not null,
  score       numeric(3,2) not null,                    -- 0 / 0.5 / 1
  elapsed_ms  integer,                                  -- 该题用时（客户端声明）；NULL = 时长不计
  answered_at timestamptz not null,                     -- 客户端声明（归日 + 补报窗口）
  received_at timestamptz not null default now(),       -- 服务端接收时刻
  day_key     date        not null,                     -- 按 Asia/Shanghai 折算
  session_id  uuid,                                     -- 一次练习会话；chain_complete 靠它防重复
  -- 接龙完成事件的变体（仅 kind='chain_complete' 时有值）：
  --   分值取决于「路线」与「作答方式」，服务端据此查表，客户端不得直接指定 XP
  chain_mode  text,                                     -- open | target
  chain_kind  text,                                     -- choice | input
  xp          integer     not null default 0,           -- **服务端**算出的分值（已应用每日裁剪）
  suspicious  boolean     not null default false,
  unique (user_id, event_id)
);

-- 约束单独加（放在 if not exists 之外，便于给已存在的表补约束）
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'xp_events_kind_chk') then
    alter table public.xp_events add constraint xp_events_kind_chk
      check (kind in ('answer', 'chain_complete'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_mode_chk') then
    -- 防线 #3 模式白名单：逐条列明七种，勿简写
    alter table public.xp_events add constraint xp_events_mode_chk
      check (mode in ('choice','spelling','matching','crossword','cloze','chain','definition'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_score_chk') then
    alter table public.xp_events add constraint xp_events_score_chk
      check (score >= 0 and score <= 1);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_elapsed_chk') then
    alter table public.xp_events add constraint xp_events_elapsed_chk
      check (elapsed_ms is null or elapsed_ms >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_xp_chk') then
    alter table public.xp_events add constraint xp_events_xp_chk check (xp >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_chain_mode_chk') then
    alter table public.xp_events add constraint xp_events_chain_mode_chk
      check (chain_mode is null or chain_mode in ('open','target'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'xp_events_chain_kind_chk') then
    alter table public.xp_events add constraint xp_events_chain_kind_chk
      check (chain_kind is null or chain_kind in ('choice','input'));
  end if;
end $$;

create index if not exists xp_events_user_day_idx  on public.xp_events (user_id, day_key);
create index if not exists xp_events_user_item_idx on public.xp_events (user_id, item_id, answered_at desc);

-- 防线 #6：一局接龙只结算一次（按 session）
create unique index if not exists xp_events_chain_uniq
  on public.xp_events (user_id, session_id)
  where kind = 'chain_complete' and session_id is not null;

-- ---- RLS：学生只读自己的；教师/开发者可读全校；**没有任何写策略** ----
-- 写只能通过下面的 security definer RPC，学生无法直接 INSERT/UPDATE/DELETE。
alter table public.xp_events enable row level security;

drop policy if exists xp_events_read_own on public.xp_events;
create policy xp_events_read_own on public.xp_events
  for select using (auth.uid() = user_id);

drop policy if exists xp_events_read_staff on public.xp_events;
create policy xp_events_read_staff on public.xp_events
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher','developer')));

-- 最小权限：TRUNCATE 不受 RLS 约束，直接收掉（同 ocr_pages 的做法）
revoke truncate, references, trigger on public.xp_events from authenticated;
revoke all on public.xp_events from anon;

comment on table public.xp_events is
  'XP 事件流水（C 档唯一事实来源）。学生只读自己的，写只能经 submit_xp_events()。xp 已应用每日 400 裁剪。';


-- ============================================================================
-- ② xp_of()：服务端算分 —— XP 表的唯一实现
--   数值见《练级与奖励体系方案.md》§2.1 / §2.1.1
-- ============================================================================
create or replace function public.xp_of(
  p_kind       text,
  p_mode       text,
  p_score      numeric,
  p_chain_mode text default null,
  p_chain_kind text default null
) returns integer
language sql
immutable
as $$
  select case
    -- 接龙：**按完成结算**，每步的 answer 事件给 0；走完一局才给分
    when p_kind = 'chain_complete' then
      case
        when p_chain_mode = 'open'   and p_chain_kind = 'choice' then 20
        when p_chain_mode = 'open'   and p_chain_kind = 'input'  then 30
        when p_chain_mode = 'target' and p_chain_kind = 'choice' then 25
        when p_chain_mode = 'target' and p_chain_kind = 'input'  then 35
        else 0
      end
    when p_mode = 'chain' then 0                    -- 接龙每一步不计 XP（只计题数与掌握度）
    when p_mode = 'definition' then
      case when p_score >= 0.9 then 10              -- 全对
           when p_score >  0   then  5              -- 部分正确
           else 2 end                               -- 错
    else
      case
        when p_score >= 0.9 then                    -- 答对
          case p_mode when 'spelling' then 8 when 'cloze' then 7 when 'crossword' then 6
                      when 'matching' then 5 when 'choice' then 4 else 0 end
        when p_score > 0 then                       -- 部分正确（取约半数）
          case p_mode when 'spelling' then 4 when 'cloze' then 4 when 'crossword' then 3
                      when 'matching' then 3 when 'choice' then 2 else 0 end
        else                                        -- 答错（保底）
          case p_mode when 'spelling' then 2 when 'cloze' then 2 when 'crossword' then 2
                      when 'matching' then 1 when 'choice' then 1 else 0 end
      end
  end
$$;

comment on function public.xp_of(text, text, numeric, text, text) is
  'XP 表唯一实现（服务端算分）。客户端只报「做了什么」，绝不报「值多少 XP」。';


-- ============================================================================
-- ③ submit_xp_events()：上报入口
--
-- 九道防线（2026-09-23 版）：
--   #1 幂等        unique(user_id,event_id) + on conflict do nothing
--   #2 补报窗口    answered_at ∈ [now()-72h, now()+5min]
--                 且**不落在已结算月份**（本月；月初 1~3 日额外允许上月）
--   #3 模式白名单  mode ∈ 七种（表约束 + 这里给友好错误）
--   #4 用时下限    <500ms ⇒ 按 500ms 计（**截断，不拒收**）；缺失 ⇒ NULL
--   #5 同题去重    同 item + 同 kind，60 秒内只收一条
--   #6 接龙唯一    unique(user_id,session_id) where kind='chain_complete'
--   #7 词条存在性  **本版暂缓**（见文件末尾说明：XP 计算不依赖 item_id）
--   #8 每日裁剪    按 day_key 累计练习 XP，当日上限 400（超出部分 xp 记 0，事件仍保留）
--   #9 异常标记    整批 elapsed_ms 全相同 ⇒ suspicious = true（只标记，不拒绝）
--
-- 原则：**宁可少算，不要丢事件** —— 除补报超窗口外，一律接收。
-- ============================================================================
create or replace function public.submit_xp_events(p_events jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid        uuid := auth.uid();
  v_n          int;
  v_rec        record;
  v_floor      date;
  v_day        date;
  v_ms         integer;
  v_xp         integer;
  v_used       integer;
  v_accepted   int := 0;
  v_duplicated int := 0;
  v_rejected   jsonb := '[]'::jsonb;
  v_all_same   boolean := false;
  v_first_ms   integer;
  v_ms_count   int := 0;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;
  if p_events is null or jsonb_typeof(p_events) <> 'array' then
    raise exception 'p_events must be a json array';
  end if;

  select count(*) into v_n from jsonb_array_elements(p_events);
  if v_n > 100 then
    raise exception 'too many events in one call (max 100)';
  end if;
  if v_n = 0 then
    return jsonb_build_object('accepted', 0, 'duplicated', 0, 'rejected', '[]'::jsonb);
  end if;

  -- 防线 #2 允许的最早日期：本月 1 日；若今天是月初 1~3 号，则再往前放一个月
  v_floor := date_trunc('month', (now() at time zone 'Asia/Shanghai'))::date;
  if extract(day from (now() at time zone 'Asia/Shanghai')) <= 3 then
    v_floor := (v_floor - interval '1 month')::date;
  end if;

  -- 防线 #9 预扫描：整批 elapsed_ms 是否全相同（脚本批量刷的典型特征）
  select count(distinct x.elapsed_ms), min(x.elapsed_ms)
    into v_ms_count, v_first_ms
    from jsonb_to_recordset(p_events) as x(elapsed_ms integer)
   where x.elapsed_ms is not null;
  v_all_same := (v_ms_count = 1) and (v_n > 3);

  for v_rec in
    select * from jsonb_to_recordset(p_events) as x(
      event_id    uuid,
      kind        text,
      item_id     text,
      mode        text,
      correct     boolean,
      score       numeric,
      elapsed_ms  integer,
      answered_at timestamptz,
      session_id  uuid,
      chain_mode  text,
      chain_kind  text
    )
  loop
    -- 必填缺失 ⇒ 拒收（这类是格式错误，不是"学生做得快"）
    if v_rec.event_id is null or v_rec.item_id is null or v_rec.mode is null
       or v_rec.kind is null or v_rec.answered_at is null or v_rec.score is null then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'missing_field');
      continue;
    end if;

    -- ★ 防线 #1 幂等 —— **必须排在所有其它检查之前**（2026-09-23 冒烟测试发现）：
    --   若放到后面，重复上报会先撞上「同题去重」而被记为 rejected: same_item_too_soon，
    --   客户端就无法区分「这条我已经收到了」与「这条被永久拒绝」，
    --   补报队列会把已成功的事件当成失败反复重试。返回 duplicated 才是正确语义。
    if exists (
      select 1 from public.xp_events e
       where e.user_id = v_uid and e.event_id = v_rec.event_id
    ) then
      v_duplicated := v_duplicated + 1;
      continue;
    end if;

    -- 防线 #2 补报窗口
    if v_rec.answered_at > now() + interval '5 minutes' then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'future_time');
      continue;
    end if;
    if v_rec.answered_at < now() - interval '72 hours' then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'too_old');
      continue;
    end if;

    -- 防线 #2b 不落在已结算月份
    v_day := (v_rec.answered_at at time zone 'Asia/Shanghai')::date;
    if v_day < v_floor then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'settled_month');
      continue;
    end if;

    -- 防线 #3 模式白名单
    if v_rec.mode not in ('choice','spelling','matching','crossword','cloze','chain','definition') then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'bad_mode');
      continue;
    end if;
    if v_rec.kind not in ('answer','chain_complete') then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'bad_kind');
      continue;
    end if;

    -- 防线 #4 用时下限：**截断，不拒收**
    v_ms := v_rec.elapsed_ms;
    if v_ms is not null and v_ms < 500 then
      v_ms := 500;
    end if;

    -- 防线 #5 同题去重：同 item 60 秒内只收一条
    --   ⚠ 仅对 kind='answer' 生效。chain_complete 的 item_id 记的是「起点」，
    --   同一天从同一个起点再开一局是完全正常的行为，不该被去重
    --   （它另有 unique(user_id, session_id) 保证同一局只结算一次）。
    if v_rec.kind = 'answer' and exists (
      select 1 from public.xp_events e
       where e.user_id = v_uid
         and e.item_id = v_rec.item_id
         and e.kind    = 'answer'
         and e.answered_at > v_rec.answered_at - interval '60 seconds'
    ) then
      v_rejected := v_rejected || jsonb_build_object('event_id', v_rec.event_id, 'reason', 'same_item_too_soon');
      continue;
    end if;

    -- 服务端算分（客户端不得指定 XP）
    v_xp := public.xp_of(
      v_rec.kind, v_rec.mode, greatest(0, least(1, coalesce(v_rec.score, 0))),
      v_rec.chain_mode, v_rec.chain_kind
    );

    -- 防线 #8 每日裁剪：只对练习 XP（本题即全部；教师奖励另表，不计入）
    if v_xp > 0 then
      select coalesce(sum(xp), 0) into v_used
        from public.xp_events
       where user_id = v_uid and day_key = v_day;
      if v_used >= 400 then
        v_xp := 0;
      elsif v_used + v_xp > 400 then
        v_xp := 400 - v_used;
      end if;
    end if;

    -- 写入（防线 #1 幂等 / #6 接龙唯一，都靠唯一索引兜底）
    begin
      insert into public.xp_events (
        user_id, event_id, kind, item_id, mode, correct, score,
        elapsed_ms, answered_at, day_key, session_id,
        chain_mode, chain_kind, xp, suspicious
      ) values (
        v_uid, v_rec.event_id, v_rec.kind, v_rec.item_id, v_rec.mode,
        coalesce(v_rec.correct, false), greatest(0, least(1, coalesce(v_rec.score, 0))),
        v_ms, v_rec.answered_at, v_day, v_rec.session_id,
        v_rec.chain_mode, v_rec.chain_kind, v_xp, v_all_same
      );
      v_accepted := v_accepted + 1;
    exception
      when unique_violation then
        v_duplicated := v_duplicated + 1;
    end;
  end loop;

  return jsonb_build_object(
    'accepted',   v_accepted,
    'duplicated', v_duplicated,
    'rejected',   v_rejected
  );
end $$;

grant execute on function public.submit_xp_events(jsonb) to authenticated;

comment on function public.submit_xp_events(jsonb) is
  'XP 事件上报（幂等）。九道防线；除补报超窗口外一律接收 —— 宁可少算，不要丢事件。';


-- ============================================================================
-- ④ get_xp_summary()：总 XP 出口（**学生端与教师端共用，防口径分叉**）
--
-- 三层全部现算、**永不落盘**：
--   练习 XP = sum(xp_events.xp)      ← 日上限 400 已在写入时应用
--   奖励 XP = sum(student_xp_bonus.amount)   ← 教师签发，**不计入日上限**
--   总 XP   = 两者相加
-- ============================================================================
create or replace function public.get_xp_summary(p_user_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid      uuid := auth.uid();
  v_target   uuid;
  v_is_staff boolean;
  v_practice integer;
  v_bonus    integer;
  v_daily    jsonb;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  v_is_staff := exists (
    select 1 from public.user_roles r
     where r.user_id = v_uid and r.role in ('teacher','developer'));

  v_target := coalesce(p_user_id, v_uid);
  if v_target <> v_uid and not v_is_staff then
    raise exception 'not allowed to read other users';
  end if;

  select coalesce(sum(xp), 0) into v_practice
    from public.xp_events where user_id = v_target;

  select coalesce(sum(amount), 0) into v_bonus
    from public.student_xp_bonus where user_id = v_target;

  select coalesce(jsonb_agg(jsonb_build_object('day_key', d.day_key, 'practice_xp', d.xp)
                            order by d.day_key), '[]'::jsonb)
    into v_daily
    from (select day_key, sum(xp) as xp
            from public.xp_events
           where user_id = v_target
           group by day_key) d;

  return jsonb_build_object(
    'practice_xp', v_practice,
    'bonus_xp',    v_bonus,
    'total_xp',    v_practice + v_bonus,
    'daily',       v_daily
  );
end $$;

grant execute on function public.get_xp_summary(uuid) to authenticated;

comment on function public.get_xp_summary(uuid) is
  '总 XP 出口。学生只能查自己，教师/开发者可查任意。练习 XP + 奖励 XP 现算相加，永不落盘。';


-- ============================================================================
-- ⑤ get_daily_study()：每日练习聚合（打卡判定用）
--
-- ⚠️ 为什么是 RPC 而不是视图：Postgres 的视图默认以**视图所有者**权限执行，
--   会**绕过基表的 RLS**。要安全就得用 security_invoker（PG 15+），
--   而本库是 AnalyticDB for PostgreSQL 兼容版、版本不保证 —— 故改用 RPC，
--   内部显式做归属校验，行为确定。
--
--   打卡达标 = questions >= 20 且 ms >= 10 分钟（判定规则**不变**，见方案 §8）
-- ============================================================================
create or replace function public.get_daily_study(
  p_user_id uuid default null,
  p_from    date default null,
  p_to      date default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid      uuid := auth.uid();
  v_target   uuid;
  v_is_staff boolean;
  v_out      jsonb;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  v_is_staff := exists (
    select 1 from public.user_roles r
     where r.user_id = v_uid and r.role in ('teacher','developer'));

  v_target := coalesce(p_user_id, v_uid);
  if v_target <> v_uid and not v_is_staff then
    raise exception 'not allowed to read other users';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
           'day_key',   d.day_key,
           'questions', d.questions,
           'ms',        d.ms,
           'correct',   d.correct
         ) order by d.day_key), '[]'::jsonb)
    into v_out
    from (
      select day_key,
             count(*) filter (where kind = 'answer')             as questions,
             -- 只累加 kind='answer' 的用时：chain_complete 不是「作答」，
             -- 万一客户端也带了用时，不应计入打卡时长。
             -- sum() 自动跳过 NULL（客户端没报用时的题），
             -- 故 coalesce 只防「全为 NULL ⇒ sum 返回 NULL」这一种情况。
             coalesce(sum(elapsed_ms) filter (where kind = 'answer'), 0) as ms,
             count(*) filter (where kind = 'answer' and correct) as correct
        from public.xp_events
       where user_id = v_target
         and (p_from is null or day_key >= p_from)
         and (p_to   is null or day_key <= p_to)
       group by day_key
    ) d;

  return v_out;
end $$;

grant execute on function public.get_daily_study(uuid, date, date) to authenticated;

comment on function public.get_daily_study(uuid, date, date) is
  '每日练习聚合（打卡判定用）。用 RPC 而非视图，避免视图绕过 RLS。';


-- ============================================================================
-- 两点说明
-- ============================================================================
-- 1) 防线 #7「词条存在性」本版**暂缓**。
--    原因：XP 的计算只依赖 mode/score/kind，**完全不依赖 item_id**，
--    所以伪造 item_id 拿不到额外 XP，它只影响「同题去重」的精度。
--    而校验 item_id 需要查 vocab_releases 的大 jsonb（慢），收益不抵成本。
--    ⇒ 若将来需要，可另加定时任务批量核对。
--
-- 2) 历史打卡迁移（checkin_baselines）**不在本脚本内**，
--    待本脚本执行完成、且前端接入验证通过后再单独生成（由 2026-09-21 审计 JSON 派生）。
