-- ============================================================================
-- 月度获奖记录（《练级与奖励体系方案》§4.5.4「结算与核验」/ §4.5.5 展示）
--
-- 用法：psql -h <host> -p 5432 -U postgres -d postgres -v ON_ERROR_STOP=1 \
--        -f db-migration-awards.sql
--
-- 无前置依赖，幂等，可重复执行（表用 if not exists、函数整体替换）。
--
-- ---------------------------------------------------------------------------
-- 为什么需要这张表
--
-- §4.5.4 的核验链条是三步：**看榜单 → 核验 → 勾「已发放」防重复**。
-- 前两步（榜单 + 月度核验表）2026-09-29 已随 P1.5 实装，**第三步没有落点** ——
-- 于是「这个月的奖发给谁了」只存在于教师的记忆里，**无法防重复发放**。
--
-- §4.5.5 另有一条依赖它：**学生端「是否获奖」** —— 而学生端现在只能显示
-- 「本月已达标 X/28 天」（那是**能否参评**，不是**是否获奖**）。
--
-- ---------------------------------------------------------------------------
-- ⚠ 设计要点一：记录必须**早于**实物发放存在
--
-- 「核验」与「把奖品交到学生手上」是**两个时刻**，中间可能隔好几天
-- （名单月初定，奖品课间发）。所以本表有**两个时间戳**：
--   · `awarded_at`   —— 教师核验后落库的时刻（§4.5.4 第 2 步）⇒ **学生端「是否获奖」看这一列**
--   · `delivered_at` —— 勾「已发放」的时刻（第 3 步）⇒ 用于防重复发放
--
-- 若只留一个「已发放」时间戳，学生在奖品到手之前会看到「未获奖」——
-- 而他其实已经赢了。那种「我明明拿了第一，为什么系统说我没获奖」是最伤信任的一种。
--
-- ---------------------------------------------------------------------------
-- ⚠ 设计要点二：`month_key` 用 `'YYYY-MM'` 文本，与 `joined_month` 同形
--
-- `get_xp_summary_all().joined_month` 也是 `'YYYY-MM'`（服务端按 Asia/Shanghai 折算）。
-- 同形 ⇒ 教师端把榜单行与获奖记录拼起来时**不需要任何日期转换**，也就没有
-- 「转换写错一个月」的机会。⚠ **时区折算必须只有服务端那一份**（§4.5.3 已立的规矩）。
--
-- ---------------------------------------------------------------------------
-- ⚠ 设计要点三：**不给「月度之星每月 1 名」加唯一约束**
--
-- §4.5.1 写了 1 名，但同一条也写了「**仍并列则都发**（人数少，成本可控）」。
-- ⇒ 并列是**合法状态**，用唯一约束去卡会让并列时第二个人的奖**存不进去**
--   （教师会遇到「勾了没反应」）。⇒ 不加约束，改由界面提示当月已列几名。
--   数据库不该替教师否决一个方案里明确允许的情况。
--
-- ---------------------------------------------------------------------------
-- ⚠ 设计要点四：只给学生发奖
--
-- 与 `grant_pending_cards()` 同一口径（§4.3.1「只发给学生」）：
-- 教职工即使出现在榜单里也不能被列奖 —— 在函数里直接拒绝，不是靠界面藏。
-- ============================================================================

-- ============================================================================
-- ① 表
-- ============================================================================
create table if not exists public.award_records (
  id           bigint      generated by default as identity primary key,
  -- 'YYYY-MM'（上海时区口径，与 get_xp_summary_all().joined_month 同形）
  month_key    text        not null check (month_key ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  user_id      uuid        not null,
  -- 'star' = 月度之星（本月 XP 增长最高）；'full_attendance' = 全勤奖（本月打卡 ≥28 天）
  award        text        not null check (award in ('star', 'full_attendance')),
  -- 核验后落库的时刻；学生端「是否获奖」以它为准
  awarded_at   timestamptz not null default now(),
  awarded_by   uuid,
  -- 勾「已发放」的时刻；null = 名单已定、实物尚未交到学生手上
  delivered_at timestamptz,
  delivered_by uuid,
  -- 同一个月、同一个人、同一个奖只有一条；重复勾选是 upsert 而不是插两条
  unique (month_key, user_id, award)
);

create index if not exists award_records_month_idx on public.award_records (month_key);
create index if not exists award_records_user_idx  on public.award_records (user_id);

alter table public.award_records enable row level security;

drop policy if exists award_records_read_own on public.award_records;
create policy award_records_read_own on public.award_records
  for select using (auth.uid() = user_id);

drop policy if exists award_records_read_staff on public.award_records;
create policy award_records_read_staff on public.award_records
  for select using (exists (
    select 1 from public.user_roles r
     where r.user_id = auth.uid() and r.role in ('teacher', 'developer')));

-- 写只能经下面的 RPC（内部做 staff 校验、目标校验、状态校验）
revoke insert, update, delete, truncate, references, trigger on public.award_records from authenticated;
revoke all on public.award_records from anon;

comment on table public.award_records is
  '月度获奖记录（§4.5.4）。awarded_at = 教师核验落库（学生端「是否获奖」看它）；'
  'delivered_at = 勾「已发放」（防重复发放）。unique(month_key,user_id,award) 保证不重复。'
  '⚠ 刻意不给「每月 1 名月度之星」加唯一约束 —— §4.5.1 允许并列都发。';

-- ============================================================================
-- ② 写入 RPC（staff-only）
-- ============================================================================
create or replace function public.set_award_record(
  p_month_key text,
  p_user_id   uuid,
  p_award     text,
  p_state     text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  if not exists (
    select 1 from public.user_roles r
     where r.user_id = v_uid and r.role in ('teacher', 'developer')
  ) then
    raise exception 'not allowed to record awards';
  end if;

  if p_month_key is null or p_month_key !~ '^\d{4}-(0[1-9]|1[0-2])$' then
    raise exception 'bad month_key: %', coalesce(p_month_key, '(null)');
  end if;

  if p_award is null or p_award not in ('star', 'full_attendance') then
    raise exception 'bad award: %', coalesce(p_award, '(null)');
  end if;

  if p_state is null or p_state not in ('awarded', 'delivered', 'none') then
    raise exception 'bad state: %', coalesce(p_state, '(null)');
  end if;

  -- 只给学生列奖（与 grant_pending_cards 同口径）
  if exists (
    select 1 from public.user_roles r
     where r.user_id = p_user_id and r.role in ('teacher', 'developer')
  ) then
    raise exception 'target is staff, not a student';
  end if;

  -- 撤销获奖（勾错了）
  if p_state = 'none' then
    delete from public.award_records a
     where a.month_key = p_month_key and a.user_id = p_user_id and a.award = p_award;
    return jsonb_build_object('ok', true, 'state', 'none',
                              'month_key', p_month_key, 'award', p_award);
  end if;

  -- 'awarded'   ⇒ 列为获奖；**并清掉 delivered_at**（它就是「撤销已发放」）
  -- 'delivered' ⇒ 列为获奖 + 标记已发放
  -- ⚠ 首次 insert 时 `awarded_at` 记的是**第一次列奖的时刻**，之后的勾选不会改写它
  --   （`on conflict` 分支只动 delivered_*）⇒ 「什么时候定的奖」不会被后来的操作抹掉。
  insert into public.award_records
         (month_key, user_id, award, awarded_at, awarded_by, delivered_at, delivered_by)
  values (p_month_key, p_user_id, p_award, now(), v_uid,
          case when p_state = 'delivered' then now() else null end,
          case when p_state = 'delivered' then v_uid else null end)
  on conflict (month_key, user_id, award) do update
     set delivered_at = case when p_state = 'delivered' then now() else null end,
         delivered_by = case when p_state = 'delivered' then v_uid else null end;

  return (
    select jsonb_build_object(
             'ok', true,
             'state', case when a.delivered_at is null then 'awarded' else 'delivered' end,
             'month_key', a.month_key,
             'award', a.award,
             'awarded_at', a.awarded_at,
             'delivered_at', a.delivered_at)
      from public.award_records a
     where a.month_key = p_month_key
       and a.user_id = p_user_id
       and a.award = p_award
  );
end $$;

comment on function public.set_award_record(text, uuid, text, text) is
  '教师核验后记录 / 撤销月度获奖（§4.5.4）。p_state：'
  'awarded = 列为获奖（并清掉已发放）；delivered = 列为获奖且已发放；none = 撤销获奖。'
  'staff-only；目标为教职工时拒绝；month_key 形如 2026-09；幂等。';

grant execute on function public.set_award_record(text, uuid, text, text) to authenticated;

-- ============================================================================
-- 复核
-- ============================================================================
\echo '== 1) 表已建、策略与权限就位（应有两行策略 + 一条表注释）=='
select c.relname as table_name,
       (select count(*) from pg_policies p where p.tablename = c.relname) as policies,
       c.relrowsecurity as rls_on
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public' and c.relname = 'award_records';

\echo ''
\echo '== 2) 函数签名 =='
select p.proname, pg_get_function_arguments(p.oid) as args, pg_get_function_result(p.oid) as returns
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'public' and p.proname = 'set_award_record';

\echo ''
\echo '== 3) 约束（应含 month_key 格式 check、award 取值 check、以及三列唯一键）=='
select con.conname, pg_get_constraintdef(con.oid) as def
  from pg_constraint con
 where con.conrelid = 'public.award_records'::regclass
 order by con.contype;

\echo ''
\echo '== 4) 现状（首次执行应为 0 行）=='
select count(*) as award_records_rows from public.award_records;
