// 把 ms-data.json 的每题起始页写进云端 ms_sections.page
// 用法：node scripts/export-ms-page.mjs && psql "<conn>" -f ms-page-import.sql
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..', '..');
const msData = JSON.parse(readFileSync(join(ROOT, 'ms-data.json'), 'utf8'));
const esc = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lines = ['-- auto-generated by app/scripts/export-ms-page.mjs', 'BEGIN;'];
let n = 0;
for (const m of msData) {
  for (const s of m.sections) {
    if (s.page == null) continue;
    lines.push(`UPDATE public.ms_sections SET page = ${s.page} WHERE session = ${esc(m.session)} AND comp = ${esc(m.comp)} AND q = ${esc(s.q)};`);
    n++;
  }
}
lines.push('COMMIT;');
const out = join(ROOT, 'ms-page-import.sql');
writeFileSync(out, lines.join('\n'));
console.log('sections with page:', n, '->', out);
