// 用本地 9699 目录的实际 ms 文件名映射 session/comp -> pdf_url，生成 ms-url-import.sql
// 对象名 = 原文件名（用户已手动按原文件名上传到 R2 桶 9699ms）
// 用法：node scripts/export-ms-url.mjs && psql "<conn>" -f ms-url-import.sql
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..', '..');
const SRC = 'C:/Users/rebir/OneDrive/文档/Miscellaneous Work/Past Paper and Specimen resources/9699';
const BASE = 'https://ms.9699vocab.cn/';
const msData = JSON.parse(readFileSync(join(ROOT, 'ms-data.json'), 'utf8'));

function toKey(f) {
  const mon = f.match(/(June|November|March)\s+(\d{4})/i);
  const code = f.match(/[SMW](\d{2})/i);
  let s = null;
  if (mon) s = { june: 's', november: 'w', march: 'm' }[mon[1].toLowerCase()] + mon[2].slice(-2);
  else if (code) s = code[0][0].toLowerCase() + code[1];
  const c = f.match(/_ms_?\s*(\d{2})\.pdf$/i) || f.match(/Mark\s+Scheme\s*(\d{2})\.pdf$/i);
  return c ? `${s}_${c[1]}` : null;
}
const byKey = new Map();
for (const f of readdirSync(SRC)) {
  const k = toKey(f);
  if (k && !byKey.has(k)) byKey.set(k, f);
}
const esc = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lines = ['-- auto-generated by app/scripts/export-ms-url.mjs', 'BEGIN;'];
let n = 0;
const missing = [];
for (const m of msData) {
  const key = `${m.session}_${m.comp}`;
  const fname = byKey.get(key);
  if (!fname) { missing.push(key); continue; }
  const url = BASE + encodeURIComponent(fname);
  lines.push(`UPDATE public.ms_sections SET pdf_url = ${esc(url)} WHERE session = ${esc(m.session)} AND comp = ${esc(m.comp)};`);
  n++;
}
lines.push('COMMIT;');
const out = join(ROOT, 'ms-url-import.sql');
writeFileSync(out, lines.join('\n'));
console.log('fill rows:', n, ' missing:', missing.length, missing.join(','));
console.log('sample long-name url for w25_11:', BASE + encodeURIComponent(byKey.get('w25_11') || ''));
console.log('->', out);
